default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: ":balloon: auto fixes by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: master
  autoupdate_schedule: weekly
  autoupdate_commit_msg: ":balloon: pre-commit autoupdate"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
      - id: ruff-format