# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help(object):
    def setupUi(self, help):
        help.setObjectName("help")
        help.resize(824, 679)
        self.gridLayout = QtWidgets.QGridLayout(help)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.TextEdit_markdown = TextEdit(help)
        self.TextEdit_markdown.setEnabled(True)
        self.TextEdit_markdown.setStyleSheet(
            "LineEdit, TextEdit, PlainTextEdit {\n"
            "    color: black;\n"
            "    background-color: rgba(255, 255, 255, 0.7);\n"
            "    border-radius: 5px;\n"
            '    /* font: 14px "Segoe UI", "Microsoft YaHei"; */\n'
            "    padding: 0px 10px;\n"
            "    selection-background-color: #00a7b3;\n"
            "}\n"
            "\n"
            "TextEdit,\n"
            "PlainTextEdit {\n"
            "    padding: 2px 3px 2px 8px;\n"
            "}\n"
            "\n"
            "LineEdit:disabled, TextEdit:disabled,\n"
            "PlainTextEdit:disabled {\n"
            "    color: rgba(0, 0, 0, 150);\n"
            "    background-color: rgba(249, 249, 249, 0.3);\n"
            "}\n"
            ""
        )
        self.TextEdit_markdown.setObjectName("TextEdit_markdown")
        self.gridLayout.addWidget(self.TextEdit_markdown, 0, 0, 1, 1)

        self.retranslateUi(help)
        QtCore.QMetaObject.connectSlotsByName(help)

    def retranslateUi(self, help):
        _translate = QtCore.QCoreApplication.translate
        help.setWindowTitle(_translate("help", "Frame"))


from qfluentwidgets import TextEdit
