# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocr_replacement_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ocrtable(object):
    def setupUi(self, ocrtable):
        ocrtable.setObjectName("ocrtable")
        ocrtable.resize(686, 605)
        self.gridLayout = QtWidgets.QGridLayout(ocrtable)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.PrimaryPushButton = PrimaryPushButton(ocrtable)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.gridLayout.addWidget(self.PrimaryPushButton, 2, 1, 1, 1)
        self.PushButton = PushButton(ocrtable)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 0, 1, 1, 1)
        self.BodyLabel_tips = BodyLabel(ocrtable)
        self.BodyLabel_tips.setTextFormat(QtCore.Qt.MarkdownText)
        self.BodyLabel_tips.setWordWrap(True)
        self.BodyLabel_tips.setObjectName("BodyLabel_tips")
        self.gridLayout.addWidget(self.BodyLabel_tips, 4, 1, 1, 1)
        self.PushButton_2 = PushButton(ocrtable)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout.addWidget(self.PushButton_2, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.TableWidget_ocr_table = TableWidget(ocrtable)
        self.TableWidget_ocr_table.setShowGrid(False)
        self.TableWidget_ocr_table.setWordWrap(False)
        self.TableWidget_ocr_table.setColumnCount(3)
        self.TableWidget_ocr_table.setObjectName("TableWidget_ocr_table")
        self.TableWidget_ocr_table.setRowCount(0)
        self.gridLayout.addWidget(self.TableWidget_ocr_table, 0, 0, 6, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 5)

        self.retranslateUi(ocrtable)
        QtCore.QMetaObject.connectSlotsByName(ocrtable)

    def retranslateUi(self, ocrtable):
        _translate = QtCore.QCoreApplication.translate
        ocrtable.setWindowTitle(_translate("ocrtable", "Frame"))
        self.PrimaryPushButton.setText(_translate("ocrtable", "保存"))
        self.PushButton.setText(_translate("ocrtable", "新增"))
        self.BodyLabel_tips.setText(_translate("ocrtable", "Body label"))
        self.PushButton_2.setText(_translate("ocrtable", "删除"))


from qfluentwidgets import BodyLabel, PrimaryPushButton, PushButton, TableWidget
