# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocr_replacement_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ocrtable(object):
    def setupUi(self, ocrtable):
        ocrtable.setObjectName("ocrtable")
        ocrtable.resize(686, 605)
        self.gridLayout = QtWidgets.QGridLayout(ocrtable)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.BodyLabel_3 = BodyLabel(ocrtable)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout.addWidget(self.BodyLabel_3, 0, 5, 1, 1)
        self.BodyLabel = BodyLabel(ocrtable)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 1, 1, 1)
        self.BodyLabel_2 = BodyLabel(ocrtable)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 0, 3, 1, 1)
        self.TableWidget_ocr_table = TableWidget(ocrtable)
        self.TableWidget_ocr_table.setShowGrid(False)
        self.TableWidget_ocr_table.setWordWrap(False)
        self.TableWidget_ocr_table.setColumnCount(3)
        self.TableWidget_ocr_table.setObjectName("TableWidget_ocr_table")
        self.TableWidget_ocr_table.setRowCount(0)
        self.gridLayout.addWidget(self.TableWidget_ocr_table, 0, 0, 5, 1)
        self.ComboBox_type = ComboBox(ocrtable)
        self.ComboBox_type.setObjectName("ComboBox_type")
        self.gridLayout.addWidget(self.ComboBox_type, 0, 2, 1, 1)
        self.LineEdit_before = LineEdit(ocrtable)
        self.LineEdit_before.setObjectName("LineEdit_before")
        self.gridLayout.addWidget(self.LineEdit_before, 0, 4, 1, 1)
        self.LineEdit_after = LineEdit(ocrtable)
        self.LineEdit_after.setObjectName("LineEdit_after")
        self.gridLayout.addWidget(self.LineEdit_after, 0, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.BodyLabel_tips = BodyLabel(ocrtable)
        self.BodyLabel_tips.setTextFormat(QtCore.Qt.MarkdownText)
        self.BodyLabel_tips.setWordWrap(True)
        self.BodyLabel_tips.setObjectName("BodyLabel_tips")
        self.gridLayout.addWidget(self.BodyLabel_tips, 3, 1, 1, 6)
        self.PushButton_delete = PushButton(ocrtable)
        self.PushButton_delete.setObjectName("PushButton_delete")
        self.gridLayout.addWidget(self.PushButton_delete, 1, 1, 1, 3)
        self.PrimaryPushButton_add = PrimaryPushButton(ocrtable)
        self.PrimaryPushButton_add.setObjectName("PrimaryPushButton_add")
        self.gridLayout.addWidget(self.PrimaryPushButton_add, 1, 4, 1, 3)
        self.gridLayout.setColumnStretch(0, 7)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 2)

        self.retranslateUi(ocrtable)
        QtCore.QMetaObject.connectSlotsByName(ocrtable)

    def retranslateUi(self, ocrtable):
        _translate = QtCore.QCoreApplication.translate
        ocrtable.setWindowTitle(_translate("ocrtable", "Frame"))
        self.BodyLabel_3.setText(_translate("ocrtable", "替换后"))
        self.BodyLabel.setText(_translate("ocrtable", "替换类型"))
        self.BodyLabel_2.setText(_translate("ocrtable", "替换前"))
        self.BodyLabel_tips.setText(_translate("ocrtable", "Body label"))
        self.PushButton_delete.setText(_translate("ocrtable", "删除选中行"))
        self.PrimaryPushButton_add.setText(_translate("ocrtable", "新增"))


from qfluentwidgets import (
    BodyLabel,
    ComboBox,
    LineEdit,
    PrimaryPushButton,
    PushButton,
    TableWidget,
)
