# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trigger_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trigger(object):
    def setupUi(self, trigger):
        trigger.setObjectName("trigger")
        trigger.resize(494, 542)
        self.gridLayout = QtWidgets.QGridLayout(trigger)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SimpleCardWidget = SimpleCardWidget(trigger)
        self.SimpleCardWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SimpleCardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SimpleCardWidget_f = SimpleCardWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_f.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget_f.setObjectName("SimpleCardWidget_f")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SimpleCardWidget_f)
        self.gridLayout_5.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget_f)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout_5.addWidget(self.StrongBodyLabel, 0, 1, 1, 1)
        self.BodyLabel = BodyLabel(self.SimpleCardWidget_f)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_5.addWidget(self.BodyLabel, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.SimpleCardWidget_f)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 0, 3, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget_f, 1, 0, 1, 1)
        self.TitleLabel_trigger = TitleLabel(self.SimpleCardWidget)
        self.TitleLabel_trigger.setObjectName("TitleLabel_trigger")
        self.gridLayout_2.addWidget(self.TitleLabel_trigger, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.SimpleCardWidget, 0, 0, 1, 1)

        self.retranslateUi(trigger)
        QtCore.QMetaObject.connectSlotsByName(trigger)

    def retranslateUi(self, trigger):
        _translate = QtCore.QCoreApplication.translate
        trigger.setWindowTitle(_translate("trigger", "Frame"))
        self.StrongBodyLabel.setText(_translate("trigger", "自动采集"))
        self.BodyLabel.setText(_translate("trigger", "自动在采集按钮出现时按下F"))
        self.TitleLabel_trigger.setText(_translate("trigger", "触发列表"))
from qfluentwidgets import BodyLabel, SimpleCardWidget, StrongBodyLabel, TitleLabel
