# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trigger_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trigger(object):
    def setupUi(self, trigger):
        trigger.setObjectName("trigger")
        trigger.resize(1022, 587)
        self.gridLayout = QtWidgets.QGridLayout(trigger)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SimpleCardWidget = SimpleCardWidget(trigger)
        self.SimpleCardWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SimpleCardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.TitleLabel_trigger = TitleLabel(self.SimpleCardWidget)
        self.TitleLabel_trigger.setObjectName("TitleLabel_trigger")
        self.gridLayout_2.addWidget(self.TitleLabel_trigger, 0, 0, 1, 1)
        self.SimpleCardWidget_f = SimpleCardWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_f.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget_f.setObjectName("SimpleCardWidget_f")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SimpleCardWidget_f)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 5, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget_f)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)
        self.BodyLabel = BodyLabel(self.SimpleCardWidget_f)
        self.BodyLabel.setProperty("darkColor", QtGui.QColor(204, 204, 204))
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.gridLayout_5.addLayout(self.verticalLayout, 2, 4, 1, 1)
        self.SwitchButton_f = SwitchButton(self.SimpleCardWidget_f)
        self.SwitchButton_f.setObjectName("SwitchButton_f")
        self.gridLayout_5.addWidget(self.SwitchButton_f, 2, 6, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget_f, 1, 0, 1, 1)
        self.SimpleCardWidget_f_2 = SimpleCardWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_f_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SimpleCardWidget_f_2.setObjectName("SimpleCardWidget_f_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.SimpleCardWidget_f_2)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 5, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.SimpleCardWidget_f_2)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.verticalLayout_2.addWidget(self.StrongBodyLabel_2)
        self.BodyLabel_2 = BodyLabel(self.SimpleCardWidget_f_2)
        self.BodyLabel_2.setProperty("darkColor", QtGui.QColor(204, 204, 204))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_2.addWidget(self.BodyLabel_2)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 2, 4, 1, 1)
        self.SwitchButton_e = SwitchButton(self.SimpleCardWidget_f_2)
        self.SwitchButton_e.setObjectName("SwitchButton_e")
        self.gridLayout_6.addWidget(self.SwitchButton_e, 2, 6, 1, 1)
        self.gridLayout_2.addWidget(self.SimpleCardWidget_f_2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.SimpleCardWidget, 0, 0, 1, 1)

        self.retranslateUi(trigger)
        QtCore.QMetaObject.connectSlotsByName(trigger)

    def retranslateUi(self, trigger):
        _translate = QtCore.QCoreApplication.translate
        trigger.setWindowTitle(_translate("trigger", "Frame"))
        self.TitleLabel_trigger.setText(_translate("trigger", "触发列表"))
        self.StrongBodyLabel.setText(_translate("trigger", "自动采集"))
        self.BodyLabel.setText(_translate("trigger", "自动在采集按钮出现时按下F键"))
        self.StrongBodyLabel_2.setText(_translate("trigger", "妮塔E技能自动qte"))
        self.BodyLabel_2.setText(_translate("trigger", "自动在qte阶段按下E键"))
from qfluentwidgets import BodyLabel, SimpleCardWidget, StrongBodyLabel, SwitchButton, TitleLabel
