# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/terminal_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Terminal(object):
    def setupUi(self, Terminal):
        Terminal.setObjectName("Terminal")
        Terminal.resize(851, 651)
        self.verticalLayoutWidget = QtWidgets.QWidget(Terminal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 851, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(self.verticalLayoutWidget)
        self.TitleLabel.setStyleSheet("margin-left: 1px;")
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setStyleSheet("border-radius: 20px;\n"
"margin-left: 3px;\n"
"margin-right: 3px;\n"
"margin-bottom: 6px;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 11)

        self.retranslateUi(Terminal)
        QtCore.QMetaObject.connectSlotsByName(Terminal)

    def retranslateUi(self, Terminal):
        _translate = QtCore.QCoreApplication.translate
        Terminal.setWindowTitle(_translate("Terminal", "Frame"))
        self.TitleLabel.setText(_translate("Terminal", "终端"))
from qfluentwidgets import TitleLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Terminal = QtWidgets.QFrame()
    ui = Ui_Terminal()
    ui.setupUi(Terminal)
    Terminal.show()
    sys.exit(app.exec_())
